# Python練習3：NumPy模組與多維陣列運算
參考: Deep Learning, 齋藤康毅，OREILLY

## 載入NumPy

In [1]:
import numpy as np

## 產生NumPy陣列 

In [2]:
x=np.array([1.0, 2.0, 3.0])

In [3]:
print(x)

[1. 2. 3.]


In [4]:
x

array([1., 2., 3.])

In [5]:
type(x)

numpy.ndarray

In [6]:
x.shape

(3,)

## NumPy算術運算

In [7]:
y=np.array([2.0, 4.0, 6.0])

In [8]:
x+y

array([3., 6., 9.])

In [9]:
x-y

array([-1., -2., -3.])

In [10]:
x/y

array([0.5, 0.5, 0.5])

In [11]:
x/2.0

array([0.5, 1. , 1.5])

## NumPy的N維陣列

In [12]:
A=np.array([[1, 2], [3, 4]])

In [13]:
print(A)

[[1 2]
 [3 4]]


In [14]:
A

array([[1, 2],
       [3, 4]])

In [15]:
A.shape

(2, 2)

In [16]:
A.dtype

dtype('int32')

In [17]:
type(A)

numpy.ndarray

In [18]:
B=np.array([[3, 0], [0, 6]])

In [19]:
A+B

array([[ 4,  2],
       [ 3, 10]])

In [20]:
A*B

array([[ 3,  0],
       [ 0, 24]])

Note: N維陣列就是由多個N-1維陣列所形成的一維陣列，例如，二維陣列就是由多個一維陣列所形成的一維陣列，三維陣列就是由多個二維陣列所形成的一維陣列。

## 廣播

In [21]:
A*10

array([[10, 20],
       [30, 40]])

In [22]:
B=np.array([10, 20])
A*B

array([[10, 40],
       [30, 80]])

In [23]:
X=np.array([[51, 55], [14,19], [0,4]])

In [24]:
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [25]:
X.shape

(3, 2)

In [26]:
X[0]

array([51, 55])

In [27]:
X[0][1]

55

In [28]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [29]:
X=X.flatten()

In [30]:
print(X)

[51 55 14 19  0  4]


In [31]:
X.shape

(6,)

In [32]:
X[np.array([0, 2, 4])]

array([51, 14,  0])

In [33]:
X>15

array([ True,  True, False,  True, False, False])

In [34]:
X[X>15]

array([51, 55, 19])

## 多維陣列的運算

In [35]:
A=np.array([1, 2, 3, 4])  # 數學上，A稱為向量
print(A)

[1 2 3 4]


In [36]:
np.ndim(A)

1

In [37]:
A.shape

(4,)

In [38]:
A.shape[0]

4

In [39]:
np.dot(A,A) #向量內積

30

In [40]:
B=np.array([[1, 2], [3,4], [5,6]]) # 數學上，B稱為3x2矩陣(三列兩行)
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
B.shape

(3, 2)

In [42]:
A=np.array([[1,2,3], [4,5,6]]) # 數學上，A稱為2x3矩陣(兩列三行)
A.shape

(2, 3)

In [43]:
np.dot(A,B)    # 矩陣相乘

array([[22, 28],
       [49, 64]])

In [44]:
np.dot(B,A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [45]:
C=np.array([[1, 2], [3,4]])
print(C)

[[1 2]
 [3 4]]


In [46]:
C.shape

(2, 2)

In [47]:
A.shape

(2, 3)

In [48]:
np.dot(A,C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
np.dot(C,A)

***

In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,2,3]])

In [ ]:
A.shape

In [ ]:
B=np.array([[1, 2], [3,4], [5,6]])
C=np.dot(A,B)
print(C)

In [ ]:
C.shape

In [ ]:
B=np.array([[1], [2], [3]])
print(B)

In [ ]:
B.shape

In [ ]:
np.ndim(B)

In [ ]:
np.dot(A,B)

In [ ]:
np.dot(B,A)

In [ ]:
A=np.array([[1, 2, 3, 4]])

In [ ]:
A.shape

In [ ]:
B=np.array([1, 2, 3, 4])

In [ ]:
np.dot(A,B)

In [ ]:
np.dot(B,A)

In [ ]:
np.dot(A,A)