<a href="https://colab.research.google.com/github/wcliao1962/2025_DL/blob/master/%E7%A5%9E%E7%B6%93%E7%B6%B2%E8%B7%AF%E8%A8%88%E7%AE%97(%E4%BA%8C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 神經網路計算(二)
## 批次學習
* 輸入層一次輸入多筆訓練資料，多筆訓練資料整批(同時)由神經網路進行計算

參考: Deep Learning, 齋藤康毅，OREILLY

In [1]:
import numpy as np

## Activation functions
### Sigmoid函數

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
X=np.array([[1.0, 0.5], [1.0, 1.5], [0.7, 0.9]])

In [4]:
sigmoid(X)

array([[0.73105858, 0.62245933],
       [0.73105858, 0.81757448],
       [0.66818777, 0.7109495 ]])

### ReLU函數

In [5]:
def relu(x):
    return np.maximum(0, x)

In [6]:
X=np.array([[1.0, 0.5], [-1.0, 1.5], [0.7, -0.9]])

In [7]:
relu(X)

array([[1. , 0.5],
       [0. , 1.5],
       [0.7, 0. ]])

### Softmax函數

In [8]:
def softmax_0(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [9]:
def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

In [10]:
x=np.array([[1.0, 0.5], [1.0, 1.5], [0.7, 0.9]])

In [11]:
np.max(x)

1.5

In [12]:
np.max(x, axis=-1, keepdims=True)

array([[1. ],
       [1.5],
       [0.9]])

In [13]:
x - np.max(x, axis=-1, keepdims=True)

array([[ 0. , -0.5],
       [-0.5,  0. ],
       [-0.2,  0. ]])

In [14]:
x = x - np.max(x, axis=-1, keepdims=True)
np.exp(x)

array([[1.        , 0.60653066],
       [0.60653066, 1.        ],
       [0.81873075, 1.        ]])

In [15]:
np.sum(np.exp(x), axis=-1, keepdims=True)

array([[1.60653066],
       [1.60653066],
       [1.81873075]])

In [16]:
softmax(x)

array([[0.62245933, 0.37754067],
       [0.37754067, 0.62245933],
       [0.450166  , 0.549834  ]])

In [17]:
softmax_0(x) # 這是錯誤的!

array([[0.19873635, 0.12053969],
       [0.12053969, 0.19873635],
       [0.16271156, 0.19873635]])

## Loss fnctions
### Cross entropy error (交叉熵誤差)

In [18]:
def cross_entropy_error_0(y, t):
    return -np.sum(t * np.log(y + 1e-7))

In [19]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [20]:
y=np.array([[0.9, 0.2], [0.6, 0.4], [0.7, 0.3]])
t=np.array([[1, 0], [0, 1], [1, 0]])

In [21]:
np.log(y + 1e-7)

array([[-0.1053604 , -1.60943741],
       [-0.51082546, -0.91629048],
       [-0.3566748 , -1.20397247]])

In [22]:
t * np.log(y + 1e-7)

array([[-0.1053604 , -0.        ],
       [-0.        , -0.91629048],
       [-0.3566748 , -0.        ]])

In [23]:
np.sum(t * np.log(y + 1e-7))

-1.3783256875025076

In [24]:
cross_entropy_error(y, t)

0.4594418958341692

In [25]:
cross_entropy_error_0(y, t)

1.3783256875025076

## 多層神經網路小批次學習
* 輸入層一次輸入多筆訓練資料，多筆訓練資料整批(同時)由神經網路進行計算

In [26]:
batch_size=3

#### 輸入層

In [27]:
X=np.array([[1.0, 0.5], [1.0, 1.5], [0.7, 0.9]])
t=np.array([[1, 0], [0, 1], [1, 0]])

In [28]:
X.shape

(3, 2)

In [29]:
X

array([[1. , 0.5],
       [1. , 1.5],
       [0.7, 0.9]])

#### 第一層

In [30]:
W1=np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
b1=np.array([0.1, 0.2, 0.3])

In [31]:
print(X.shape)
print(W1.shape)
print(b1.shape)

(3, 2)
(2, 3)
(3,)


In [32]:
Z1=np.dot(X, W1)+b1
print(Z1)

[[0.3  0.7  1.1 ]
 [0.5  1.1  1.7 ]
 [0.35 0.77 1.19]]


In [33]:
H1=sigmoid(Z1)
print(H1)

[[0.57444252 0.66818777 0.75026011]
 [0.62245933 0.75026011 0.84553473]
 [0.58661758 0.68352089 0.76674106]]


#### 第二層

In [34]:
W2=np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
b2=np.array([0.1, 0.2])

In [35]:
print(H1.shape)
print(W2.shape)
print(b2.shape)

(3, 3)
(3, 2)
(2,)


In [36]:
Z2=np.dot(H1, W2)+b2
print(Z2)

[[0.51615984 1.21402696]
 [0.56595837 1.33143463]
 [0.52538826 1.23645212]]


In [37]:
H2=relu(Z2)
print(H2)

[[0.51615984 1.21402696]
 [0.56595837 1.33143463]
 [0.52538826 1.23645212]]


#### 第三層(輸出層)

In [38]:
W3=np.array([[0.1, 0.3], [0.2, 0.4]])
b3=np.array([0.1, 0.2])

In [39]:
print(H2.shape)
print(W3.shape)
print(b3.shape)

(3, 2)
(2, 2)
(2,)


In [41]:
Z3=np.dot(H2, W3)+b3
print(Z3)

[[0.39442138 0.84045873]
 [0.42288276 0.90236136]
 [0.39982925 0.85219732]]


In [42]:
y_hat=softmax(Z3)
print(y_hat)

[[0.39030333 0.60969667]
 [0.38237525 0.61762475]
 [0.38879788 0.61120212]]


### Cross entropy error (交叉熵誤差)

In [43]:
y=[[1, 0], [0, 1], [1, 0]]

In [44]:
cross_entropy_error(y_hat, y)

0.7891334193966603